name: "Bug Report"

description: "Please submit a bug report to help us improve our project."

labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        Thank you for writing a bug report for our project! 😄

        💡 Before creating a bug report

        New to bug reporting? See [bug reporting guidelines](https://github.com/Jineeary/meetro/blob/main/CONTRIBUTING.md#did-you-find-a-bug)!

        If you have any other questions, please contact us by [e-mail](duswlsgodqhr@naver.com) or [open chat](https://open.kakao.com/o/sIczM5Yg)!

        ![image](https://github.com/user-attachments/assets/dac20012-5dc8-4476-b74a-482d5549bd37)

  - type: textarea
    id: "problem_description"
    attributes:
      label: "Can someone help me? 🤔"
      description: |
        Is there a problem? What kind of help do you want? 
        Figuring out the right person to tag @ will fix the problem faster!

        I'll give you an answer as soon as possible! 😄❤️

        Did you find any problems with the project? **Project Leader** : @scarlet0411

        Is there a problem with the model? **Code Manager** : @greatdsyeomye

        Do you think there's a problem with the data? **Data Collector** : @dhormfo

        Did you find any problems on the website? **Website Creator** : @jineeary

    validations:
      required: true
